all: q1 q2 q3 q4

q1: Q1/main.c
	gcc -o Q1/question1 Q1/main.c

q2: Q2/main.c
	gcc -o Q2/question2 Q2/main.c

q3: Q3/main.c
	gcc -o Q3/question3 Q3/main.c

q4: Q4/main.c
	gcc -lm -o Q4/question4 Q4/main.c

clean:
	rm -f Q1/*.o Q1/question1 Q2/*.o Q2/question2 Q3/*.o Q3/question3 Q4/*.o Q4/question4 
