all: q1 q2 q3 q4

q1: P1A1/main.c
	gcc -o P1A1/question1 P1A1/main.c

q2: P2A1/main.c
	gcc -o P2A1/question2 P2A1/main.c

q3: P3A1/main.c
	gcc -o P3A1/question3 P3A1/main.c

q4: P4A1/main.c
	gcc -lm -o P4A1/question4 P4A1/main.c

clean:
	rm -f P1A1/*.o P1A1/question1 P2A1/*.o P2A1/question2 P3A1/*.o P3A1/question3 P4A1/*.o P4A1/question4 
